language: ruby
rvm:
  - 2.1.3
services:
  - postgresql
before_script:
  - psql -c 'create database jorgediasteste;' -U postgres
script:
  - bundle exec rake db:migrate:reset RAILS_ENV=test -- trace
  - bundle exec rspec -f d spec
