default: &default
  adapter: postgresql
  host: localhost
  username: postgres
  password: 123456
  pool: 5
  timeout: 5000

default: &dev
  adapter: postgresql
  host: localhost 
  username: postgres
  password: 123456 
  pool: 5
  timeout: 5000

development:
  <<: *dev
  database: jorgedias

test:
  <<: *dev
  database: jorgediasteste

production:
  <<: *default
  database: jorgedias